# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-10-21 16:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enName', models.CharField(max_length=200)),
                ('char_type', models.IntegerField()),
                ('isProperty', models.BooleanField(default=False)),
                ('specify', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemObserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obeservation_number', models.IntegerField(blank=True, null=True)),
                ('obs_time', models.DateField()),
                ('shop_type', models.IntegerField()),
                ('shop_identifier', models.CharField(max_length=200)),
                ('flag', models.CharField(choices=[('E', 'E'), ('O', 'O')], max_length=4)),
                ('discount', models.CharField(choices=[('N', 'N'), ('R', 'R'), ('Q', 'Q'), ('T', 'T')], max_length=4)),
                ('observed_price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('observed_quantity', models.DecimalField(decimal_places=2, max_digits=25)),
                ('obs_comment', models.CharField(blank=True, max_length=300)),
                ('specified_characteristics', models.CharField(blank=True, max_length=400)),
                ('shop_own_brand', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='observation_pic_uploads/')),
                ('barcode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservedCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=200)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Characteristic')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Observation')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, max_length=4)),
                ('dataflowID', models.CharField(max_length=100)),
                ('current', models.BooleanField()),
                ('default_vat', models.DecimalField(decimal_places=4, default=0.24, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Observation')),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCommentary',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='survey.Item')),
                ('seasonality', models.BooleanField(default=False)),
                ('representativity', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, default='', max_length=300)),
                ('vat', models.DecimalField(decimal_places=4, default=0.24, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='userobservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together=set([('code', 'year')]),
        ),
        migrations.AddField(
            model_name='observation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Item'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_observer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='itemobserver',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Item'),
        ),
        migrations.AddField(
            model_name='itemobserver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='collectorcomment',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Observer'),
        ),
        migrations.AddField(
            model_name='collectorcomment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Item'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Item'),
        ),
        migrations.CreateModel(
            name='Observation4PriceComp',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('survey.observation',),
        ),
        migrations.CreateModel(
            name='ObservationBeta',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('survey.observation',),
        ),
        migrations.AlterUniqueTogether(
            name='collectorcomment',
            unique_together=set([('collector', 'item')]),
        ),
    ]
