# Generated by Django 2.2.16 on 2020-10-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='picture',
        ),
        migrations.CreateModel(
            name='ObservationPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='observation_pic_uploads/')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Observation')),
            ],
        ),
    ]
