# Generated by Django 2.2.16 on 2020-10-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20201027_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationpicture',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='observation_pic_uploads/'),
        ),
    ]
