# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170406_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='survey',
        ),
        migrations.AddField(
            model_name='observation',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
            preserve_default=False,
        ),
    ]
