# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_observedcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedcharacteristic',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
