# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_remove_observation_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonality', models.BooleanField(default=False)),
                ('representivity', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Item')),
            ],
        ),
    ]
