# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_itemcommentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcommentary',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemcommentary',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='survey.Item'),
        ),
    ]
