# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20170502_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcommentary',
            name='vat',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
