# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20170502_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcommentary',
            name='representivity',
        ),
        migrations.AddField(
            model_name='itemcommentary',
            name='representativity',
            field=models.BooleanField(default=True),
        ),
    ]
