# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20170502_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='current',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
