# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_survey_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='value',
            new_name='observed_price',
        ),
    ]
