# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20170526_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/99601afa-9e02-4237-b77f-0ad9f7984fe8'),
        ),
    ]
