# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/8163f2ed-34f3-44f1-b49b-92142757b096'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_price',
            field=models.DecimalField(decimal_places=1, max_digits=25),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_quantity',
            field=models.DecimalField(decimal_places=1, max_digits=25),
        ),
    ]
