# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20171030_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/b39e71df-e28e-44ca-aeab-f9be8c6b420f'),
        ),
    ]
