# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20180305_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/812707d4-1574-483b-b7ba-5a8bbd2e88ca'),
        ),
    ]
