# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20180305_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/51206a97-1a27-405d-bac0-564d0efb4328'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='discount',
            field=models.CharField(choices=[('N', 'N'), ('R', 'R'), ('Q', 'Q'), ('T', 'T')], max_length=4),
        ),
    ]
