# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_auto_20180305_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/ab8b4b8b-fb4d-4503-b483-7f12145f8941'),
        ),
    ]
