# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20180411_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='default_vat',
            field=models.DecimalField(decimal_places=4, default=0.24, max_digits=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/29d833c8-8e36-4a36-be5e-48abe2ebe182'),
        ),
    ]
