# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_auto_20180420_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation4PriceComp',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('survey.observation',),
        ),
        migrations.CreateModel(
            name='ObservationBeta',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('survey.observation',),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/5fb3afc0-c0d0-485c-b639-7c251d3d3bbd'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
