# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_auto_20190717_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pic_uploads/'),
        ),
    ]
