# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_auto_20190719_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='barcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
