# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_merge_20190729_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Observer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Item')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='collectorcomment',
            unique_together=set([('collector', 'item')]),
        ),
    ]
