# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obeservation_number', models.IntegerField(blank=True)),
                ('obs_time', models.DateTimeField()),
                ('shop_type', models.IntegerField()),
                ('shop_identifier', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=4)),
                ('discount', models.CharField(max_length=4)),
                ('value', models.DecimalField(decimal_places=4, max_digits=25)),
                ('brand', models.CharField(max_length=200)),
                ('observed_quantity', models.DecimalField(decimal_places=4, max_digits=25)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perap.Item')),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
