# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0003_auto_20170403_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='obs_time',
        ),
    ]
