# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0005_observation_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='obs_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
