# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0006_observation_obs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='characteristics',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='observation',
            name='obs_comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
