# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0007_auto_20170403_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='item',
            name='characteristics',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
