# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0008_auto_20170404_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enName', models.CharField(max_length=200)),
                ('char_type', models.IntegerField()),
                ('isProperty', models.BooleanField()),
                ('specify', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='item',
            name='characteristics',
            field=models.ManyToManyField(related_name='characteristics', to='perap.Characteristic'),
        ),
    ]
