# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0009_auto_20170404_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perap.Item'),
            preserve_default=False,
        ),
    ]
