# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0010_auto_20170404_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='isProperty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='specify',
            field=models.BooleanField(default=False),
        ),
    ]
