# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perap', '0012_auto_20170405_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='item',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='userobservation',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='userobservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='UserObservation',
        ),
    ]
