# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enName', models.CharField(max_length=200)),
                ('char_type', models.IntegerField()),
                ('isProperty', models.BooleanField(default=False)),
                ('specify', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obeservation_number', models.IntegerField(blank=True)),
                ('obs_time', models.DateField()),
                ('shop_type', models.IntegerField()),
                ('shop_identifier', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=4)),
                ('discount', models.CharField(max_length=4)),
                ('value', models.DecimalField(decimal_places=4, max_digits=25)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('observed_quantity', models.DecimalField(decimal_places=4, max_digits=25)),
                ('obs_comment', models.CharField(blank=True, max_length=300)),
                ('specified_characteristics', models.CharField(blank=True, max_length=400)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbeto.Item')),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbeto_observer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbeto.Observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbeto_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='characteristic',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbeto.Item'),
        ),
    ]
